mklink /H RenderChunk\src\bgfx_shader.sh src\bgfx_shader.sh
mklink /H RenderChunk\src\RenderChunk.fragment.sc src\RenderChunk.fragment.sc
mklink /H RenderChunk\src\RenderChunk.varying.def.sc src\RenderChunk.varying.def.sc
mklink /H RenderChunk\src\RenderChunk.vertex.sc src\RenderChunk.vertex.sc
mklink /H RenderChunk_dxil2spirv2hlsl\src\bgfx_shader.sh src\bgfx_shader.sh
mklink /H RenderChunk_dxil2spirv2hlsl\src\RenderChunk.fragment.sc src\RenderChunk.fragment.sc
mklink /H RenderChunk_dxil2spirv2hlsl\src\RenderChunk.varying.def.sc src\RenderChunk.varying.def.sc
mklink /H RenderChunk_dxil2spirv2hlsl\src\RenderChunk.vertex.sc src\RenderChunk.vertex.sc
mklink /H RenderChunk_ios\src\bgfx_shader.sh src\bgfx_shader.sh
mklink /H RenderChunk_ios\src\RenderChunk.fragment.sc src\RenderChunk.fragment.sc
mklink /H RenderChunk_ios\src\RenderChunk.varying.def.sc src\RenderChunk.varying.def.sc
mklink /H RenderChunk_ios\src\RenderChunk.vertex.sc src\RenderChunk.vertex.sc